"use client";

import { Eye, EyeOff, Image as ImageIcon, Plus, Save, Star, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { useDebouncedAutosave } from "@/hooks/useDebouncedAutosave";
import type { RuleArticle, RuleCategory, RulebookData } from "@/types/rulebook";

const fallbackCategories: RuleCategory[] = ["combate", "testes", "atributos", "defesa-dano", "personagem", "progressao", "habilidades", "armaduras", "equipamentos", "npcs", "regras-da-casa"];

export function RulesView({ data, action, onOpened, focusId }: { data: RulebookData; action: (payload: Record<string, unknown>) => Promise<unknown>; onOpened: (type: string, id: string, name: string) => void; focusId?: string }) {
  const [selectedId, setSelectedId] = useState(focusId ?? data.rules[0]?.id ?? "");
  const [filter, setFilter] = useState("");
  useEffect(() => { if (focusId && data.rules.some((item) => item.id === focusId)) setSelectedId(focusId); }, [data.rules, focusId]);
  const selected = data.rules.find((item) => item.id === selectedId) ?? data.rules[0];
  const visible = useMemo(() => data.rules.filter((item) => !filter || `${item.title} ${item.summary} ${item.tags.join(" ")}`.toLowerCase().includes(filter.toLowerCase())), [data.rules, filter]);
  function select(rule: RuleArticle) { setSelectedId(rule.id); onOpened("rule", rule.id, rule.title); }
  async function createRule() { const category = (data.systemConfig?.ruleCategories?.[0] ?? "regras-da-casa") as RuleCategory; const item: RuleArticle = { id: `rule-${Date.now()}`, category, title: "Nova regra", summary: "Resumo da regra.", content: "Descreva a regra aqui.", tags: [], meta: { visibility: "master", favorite: false, archived: false } }; await action({ action: "upsert-rule", systemId: data.activeSystemId, tableId: data.activeTableId, item }); setSelectedId(item.id); onOpened("rule", item.id, item.title); }

  return <div className="grid h-full grid-cols-[300px_1fr] overflow-hidden"><aside className="overflow-y-auto border-r border-zinc-800 bg-zinc-900/60 p-4"><div className="flex gap-2"><input value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Filtrar regras" className="field" /><button onClick={() => void createRule()} className="icon-button" title="Nova regra"><Plus className="h-4 w-4" /></button></div><div className="mt-4 space-y-2">{visible.map((rule) => <button key={rule.id} onClick={() => select(rule)} className={`flex w-full items-center gap-3 rounded-lg border p-3 text-left ${selected?.id === rule.id ? "border-amber-500/50 bg-amber-500/10" : "border-zinc-800 bg-zinc-950 hover:border-zinc-700"}`}>{rule.meta?.imageUrl && <img src={rule.meta.imageUrl} alt="" referrerPolicy="no-referrer" className="h-9 w-9 rounded-lg object-cover" />}<div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate font-medium text-zinc-200">{rule.title}</p>{rule.meta?.favorite && <Star className="h-3.5 w-3.5 shrink-0 fill-amber-300 text-amber-300" />}</div><p className="mt-1 text-xs text-zinc-500">{rule.category}</p></div></button>)}</div></aside><section className="overflow-y-auto p-6">{selected ? <RuleEditor key={selected.id} rule={selected} data={data} action={action} /> : <Empty />}</section></div>;
}

function RuleEditor({ rule, data, action }: { rule: RuleArticle; data: RulebookData; action: (payload: Record<string, unknown>) => Promise<unknown> }) {
  const [draft, setDraft] = useState(rule); const [tagsText, setTagsText] = useState(rule.tags.join(", ")); const categories = (data.systemConfig?.ruleCategories ?? fallbackCategories) as RuleCategory[];
  const payload = useMemo(() => ({ ...draft, tags: tagsText.split(",").map((item) => item.trim()).filter(Boolean) }), [draft, tagsText]);
  async function saveRule(next: RuleArticle) { await action({ action: "upsert-rule", systemId: data.activeSystemId, tableId: data.activeTableId, item: next }); }
  const autosave = useDebouncedAutosave(payload, saveRule, 1000);
  async function toggleFavorite() { const next: RuleArticle = { ...draft, meta: { ...draft.meta, favorite: !draft.meta?.favorite } }; setDraft(next); await saveRule({ ...next, tags: tagsText.split(",").map((item) => item.trim()).filter(Boolean) }); }
  async function toggleVisibility() { const visibility = draft.meta?.visibility === "players" ? "master" : "players"; const next: RuleArticle = { ...draft, meta: { ...draft.meta, visibility } }; setDraft(next); await saveRule({ ...next, tags: tagsText.split(",").map((item) => item.trim()).filter(Boolean) }); }
  return <div className="item-editor-scope mx-auto max-w-4xl space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.2em] text-amber-400">Regra do sistema</p><h2 className="mt-1 text-2xl font-bold">{draft.title}</h2></div><div className="flex gap-2"><button onClick={() => void toggleFavorite()} className="icon-button"><Star className={`h-4 w-4 ${draft.meta?.favorite ? "fill-amber-300 text-amber-300" : ""}`} /></button><button onClick={() => void toggleVisibility()} className="icon-button">{draft.meta?.visibility === "players" ? <Eye className="h-4 w-4" /> : <EyeOff className="h-4 w-4" />}</button><button onClick={async () => { if (prompt(`Para excluir “${rule.title}”, digite o título exatamente:`) === rule.title) await action({ action: "delete-rule", systemId: data.activeSystemId, tableId: data.activeTableId, id: rule.id, name: rule.title }); }} className="icon-button text-red-300"><Trash2 className="h-4 w-4" /></button></div></div>
    <div className="grid gap-4 rounded-xl border border-zinc-800 bg-zinc-900/50 p-4 md:grid-cols-[180px_1fr]">{draft.meta?.imageUrl ? <img src={draft.meta.imageUrl} alt={draft.meta.imageAlt ?? draft.title} referrerPolicy="no-referrer" className="h-40 w-full rounded-xl object-cover" /> : <div className="flex h-40 items-center justify-center rounded-xl border border-dashed border-zinc-800 bg-zinc-950 text-zinc-700"><ImageIcon className="h-8 w-8" /></div>}<div><label className="form-label">URL da imagem<input className="field mt-2" value={draft.meta?.imageUrl ?? ""} onChange={(event) => setDraft({ ...draft, meta: { ...draft.meta, imageUrl: event.target.value } })} placeholder="https://i.imgur.com/imagem.png" /></label><label className="form-label mt-3">Texto alternativo<input className="field mt-2" value={draft.meta?.imageAlt ?? ""} onChange={(event) => setDraft({ ...draft, meta: { ...draft.meta, imageAlt: event.target.value } })} /></label></div></div>
    <label className="form-label">Título<input className="field mt-2" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><div className="grid gap-3 md:grid-cols-2"><label className="form-label">Categoria<select className="field mt-2" value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value as RuleCategory })}>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="form-label">Tags<input className="field mt-2" value={tagsText} onChange={(event) => setTagsText(event.target.value)} placeholder="combate, crítico, casa" /></label></div><label className="form-label">Resumo<textarea className="field mt-2" rows={3} value={draft.summary} onChange={(event) => setDraft({ ...draft, summary: event.target.value })} /></label><label className="form-label">Conteúdo<textarea className="field mt-2 min-h-[360px]" value={draft.content} onChange={(event) => setDraft({ ...draft, content: event.target.value })} /></label><div className="flex items-center justify-between gap-3 rounded-lg border border-zinc-800 bg-zinc-900/60 p-3 text-xs text-zinc-500"><span>{autosave === "dirty" ? "● Alterações não salvas" : autosave === "saving" ? "Salvando..." : autosave === "error" ? "Erro no autosave" : "✓ Salvo automaticamente"} • {draft.meta?.visibility === "players" ? "visível aos jogadores" : "somente mestre"}</span><button onClick={() => void saveRule(payload)} className="secondary-button"><Save className="h-3.5 w-3.5" />Salvar agora</button></div>
  </div>;
}

function Empty() { return <div className="flex h-full items-center justify-center text-sm text-zinc-500">Crie ou selecione uma regra.</div>; }
